Repository andr3felipe/alfabetizAi-react, pull requests merged in 2024-01, with the labels that each got.

#2 add: pages and navigation
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/components/HeaderMobile/index.tsx
  src/components/NavButton/index.tsx
  src/pages/app/Classroom/index.tsx
  src/pages/app/Home/index.tsx
  src/pages/app/Login/index.tsx
  src/pages/app/Register/index.tsx
  src/routes.tsx
Labels: enhancement

#9 add: Advantages and benefits section
  src/pages/app/Home/index.tsx
  src/pages/app/Home/styles.ts
Labels: enhancement

#10 fix: header navbutton bg
  src/components/Header/index.tsx
Labels: bug

#15 fix: colors contrast and change backgroundColor name
  src/assets/kids_studying.png
  src/assets/kids_studying.svg
  src/assets/woman-phone.png
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/components/NavButton/index.tsx
  src/components/NavButton/styles.ts
  src/pages/app/Home/index.tsx
  src/pages/app/Home/styles.ts
  src/styles/themes/default.ts
Labels: bug

#16 fix: meta tags, last section title size, position and size on Our com…
  index.html
  src/pages/app/Home/index.tsx
  src/pages/app/Home/styles.ts
Labels: bug

#17 Feat/login page
  package-lock.json
  package.json
  src/db/db.json
  src/pages/app/Login/index.tsx
  src/pages/app/Login/styles.ts
Labels: enhancement

#18 docs: update readme
  README.md
  src/assets/paleta_cores.png
Labels: documentation

#19 fix: headerMobile menu icon and links color
  src/components/Header/index.tsx
  src/components/HeaderMobile/index.tsx
Labels: bug

#22 fix: imgs heigth and width, email validation message on register page
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/pages/app/Home/index.tsx
  src/pages/app/Register/index.tsx
Labels: bug

#26 docs: update readme, lighthouse optimization
  README.md
  src/assets/lp_lighthouse.webp
Labels: documentation

#33 fix: remove focus outline style from global, NavButton and Header lin…
  src/components/Header/styles.ts
  src/components/NavButton/styles.ts
  src/styles/themes/global.ts
Labels: bug

#34 add: login modal
  src/components/Button/styles.ts
  src/components/Header/index.tsx
  src/components/Header/styles.ts
Labels: enhancement

#35 add: close modal and set role on localstorage onclick navlink
  src/components/Header/index.tsx
Labels: enhancement

#36 add: role select on login form
  src/pages/app/Login/index.tsx
  src/pages/app/Login/styles.ts
Labels: enhancement

#40 docs: update readme, backend requirements report
  README.md
Labels: documentation

#42 docs: update readme, backend requirements report
  README.md
Labels: documentation

#44 add: classroom basic layout
  src/assets/classroom_bg.webp
  src/pages/auth/Classroom/index.tsx
  src/pages/auth/Classroom/styles.ts
Labels: enhancement
